name = "JitEngine"
uuid = "c9dac84c-03a7-4281-847c-273c221d165d"
version = "0.3.0"
authors = ["Shahriar Iravanian <siravan@svtsim.com>"]

[deps]
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
IfElse = ">= 0.1"
JSON = ">= 0.1"
Mmap = "1"
ModelingToolkit = "9, 10"
Pkg = "1.11.0"
PrecompileTools = "1.3.3"
SymbolicUtils = "3"
Symbolics = "5, 6"
